modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="supernatural"
version="2.11.0"
displayName="Supernatural"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
credits="Jusey1, Piero, nojustgavin, AuraBraixen_4412"
authors="Jusey1"
description="Adds Supernatural mobs like vampires and spirits."

[[dependencies.supernatural]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




