modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="supernatural"
version="2.12.0"
displayName="Supernatural"
displayURL="https://mcreator.net"
credits="Jusey1, Burack"
authors="Jusey1"
description="Supernatural"

[[dependencies.supernatural]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




