modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="supernatural"
version="3.3.5"
displayName="Supernatural"
displayURL="https://discord.gg/QWRjTW3D5n"
logoFile="logo.png"
authors="Jusey1"
credits="Jusey1, Burack, Aura, Myahster, Void, Lu"
description="Adds supernatural entities, blocks, & items."
enumExtensions="META-INF/enumextensions.json"


[[dependencies.supernatural]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"

[[dependencies.supernatural]]
    modId="amendments"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"